import Head from "next/head";
import styles from "../styles/Home.module.css";

import MaterialTable from "material-table";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ maxWidth: "100%" }}>
        <MaterialTable
          columns={[
            { title: "Ad", field: "name" },
            { title: "Soyad", field: "surname" },
            { title: "Dogum", field: "birthYear", type: "numeric" },
            {
              title: "Dogum Yeri",
              field: "birthCity",
              lookup: { 34: "IStan", 63: "San" },
            },
          ]}
          data={[
            {
              name: "Mehmet",
              surname: "Baran",
              birthYear: 1987,
              birthCity: 63,
            },
          ]}
          title="Demo Title"
        />
      </div>
    </div>
  );
}
